databases:
  - name: clinicapp
    databaseName: clinicapp_production
    user: clinicapp

services:
  - type: web
    name: clinicapp
    runtime: ruby
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: clinicapp
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false